### ISSUE TITLE
Address concerns about the use of eSync as an OTA solution for non-AWF members

### ISSUE THREAD

**Issue by ghost** [autowarefoundation/AutowareProjects#33]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Confirm if eSync has an open-source or free tier available that will allow non-AWF members to use their OTA solution with Open AD Kit.

### Purpose

One of the stated objectives of the Open AD Kit project is to "deliver an autonomous drive quick starter kit comprising of hardware, system software, communication middleware, Autoware and cloud connectivity to boot strap cloud native automotive development". Although the eSync license covers AWF members, what about non-AWF members who want to use the Open AD Kit?

### Definition of done

- [x] Confirm the situation around eSync's license for non-AWF members - is there any open source or free tier solution?
- [x] Confirm how AWF members will get access to eSync's solution

**Comment by samet-kutuk** [comment]
_Confirm the situation around eSync's license for non-AWF members - is there any open source or free tier solution?_
Done.
Since the Autoware project usage is not limited to only AWF members, non-AWF members will be made available to use eSync's OTA capability, once it's implemented in the Open AD Kit. This is a general rule of thumb but technicalities will be detailed once the implementation is completed.

**Comment by samet-kutuk** [comment]
_Confirm how AWF members will get access to eSync's solution
Done.
eSync's SDK is currently running on major public cloud vendors (such as AWS, Microsoft Azure, Google Cloud). For AWF members to access the solution, a separate SDK (with the same capabilities) will be made available to use through AWF hosted cloud instances
